name: main
on: push
env:
  GO_VERSION: 1.18.3
  
jobs: 
  build-infra:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2.1.3
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: test get-function
        run: cd ronit-cloud-resume/get-function && go test -v ./ && cd ../../
      - name: test put-function
        run: cd ronit-cloud-resume/put-function && go test -v ./ && cd ../../
